SET time_zone='America/Lima';

DROP EVENT IF EXISTS ANULAR_PRESTAMOS_SIN_RETIRO;
DROP EVENT IF EXISTS COLOCAR_USUARIOS_DEUDORES;


CREATE EVENT ANULAR_PRESTAMOS_SIN_RETIRO
ON SCHEDULE
    EVERY 1 DAY
    STARTS '2023-11-21 00:01:00'
    COMMENT 'Ejecutar procedimiento cada dia'
DO
    CALL REVISAR_PRESTAMOS_X_ANULAR();
    

CREATE EVENT COLOCAR_USUARIOS_DEUDORES
ON SCHEDULE
    EVERY 1 DAY
    STARTS '2023-11-21 00:02:00'
    COMMENT 'Ejecutar procedimiento cada dia'
DO
    CALL REVISAR_USUARIOS_DEUDORES();
