//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ULearn.StaffWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.web.ulearn/", ConfigurationName="StaffWS.StaffWS")]
    public interface StaffWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/StaffWS/buscarFotoPerfilRequest", ReplyAction="http://webservices.web.ulearn/StaffWS/buscarFotoPerfilResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ULearn.StaffWS.buscarFotoPerfilResponse buscarFotoPerfil(ULearn.StaffWS.buscarFotoPerfilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/StaffWS/buscarFotoPerfilRequest", ReplyAction="http://webservices.web.ulearn/StaffWS/buscarFotoPerfilResponse")]
        System.Threading.Tasks.Task<ULearn.StaffWS.buscarFotoPerfilResponse> buscarFotoPerfilAsync(ULearn.StaffWS.buscarFotoPerfilRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/StaffWS/eliminarAdministradorRequest", ReplyAction="http://webservices.web.ulearn/StaffWS/eliminarAdministradorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ULearn.StaffWS.eliminarAdministradorResponse eliminarAdministrador(ULearn.StaffWS.eliminarAdministradorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/StaffWS/eliminarAdministradorRequest", ReplyAction="http://webservices.web.ulearn/StaffWS/eliminarAdministradorResponse")]
        System.Threading.Tasks.Task<ULearn.StaffWS.eliminarAdministradorResponse> eliminarAdministradorAsync(ULearn.StaffWS.eliminarAdministradorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/StaffWS/eliminarEncargadoRequest", ReplyAction="http://webservices.web.ulearn/StaffWS/eliminarEncargadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ULearn.StaffWS.eliminarEncargadoResponse eliminarEncargado(ULearn.StaffWS.eliminarEncargadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/StaffWS/eliminarEncargadoRequest", ReplyAction="http://webservices.web.ulearn/StaffWS/eliminarEncargadoResponse")]
        System.Threading.Tasks.Task<ULearn.StaffWS.eliminarEncargadoResponse> eliminarEncargadoAsync(ULearn.StaffWS.eliminarEncargadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/StaffWS/listarTodosEncargadosRequest", ReplyAction="http://webservices.web.ulearn/StaffWS/listarTodosEncargadosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ULearn.StaffWS.listarTodosEncargadosResponse listarTodosEncargados(ULearn.StaffWS.listarTodosEncargadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/StaffWS/listarTodosEncargadosRequest", ReplyAction="http://webservices.web.ulearn/StaffWS/listarTodosEncargadosResponse")]
        System.Threading.Tasks.Task<ULearn.StaffWS.listarTodosEncargadosResponse> listarTodosEncargadosAsync(ULearn.StaffWS.listarTodosEncargadosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/StaffWS/insertarEncargadoRequest", ReplyAction="http://webservices.web.ulearn/StaffWS/insertarEncargadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ULearn.StaffWS.insertarEncargadoResponse insertarEncargado(ULearn.StaffWS.insertarEncargadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/StaffWS/insertarEncargadoRequest", ReplyAction="http://webservices.web.ulearn/StaffWS/insertarEncargadoResponse")]
        System.Threading.Tasks.Task<ULearn.StaffWS.insertarEncargadoResponse> insertarEncargadoAsync(ULearn.StaffWS.insertarEncargadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/StaffWS/hallarAdministradorPorIdRequest", ReplyAction="http://webservices.web.ulearn/StaffWS/hallarAdministradorPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ULearn.StaffWS.hallarAdministradorPorIdResponse hallarAdministradorPorId(ULearn.StaffWS.hallarAdministradorPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/StaffWS/hallarAdministradorPorIdRequest", ReplyAction="http://webservices.web.ulearn/StaffWS/hallarAdministradorPorIdResponse")]
        System.Threading.Tasks.Task<ULearn.StaffWS.hallarAdministradorPorIdResponse> hallarAdministradorPorIdAsync(ULearn.StaffWS.hallarAdministradorPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/StaffWS/listarEncargadosXUsuarioNombreRequest", ReplyAction="http://webservices.web.ulearn/StaffWS/listarEncargadosXUsuarioNombreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ULearn.StaffWS.listarEncargadosXUsuarioNombreResponse listarEncargadosXUsuarioNombre(ULearn.StaffWS.listarEncargadosXUsuarioNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/StaffWS/listarEncargadosXUsuarioNombreRequest", ReplyAction="http://webservices.web.ulearn/StaffWS/listarEncargadosXUsuarioNombreResponse")]
        System.Threading.Tasks.Task<ULearn.StaffWS.listarEncargadosXUsuarioNombreResponse> listarEncargadosXUsuarioNombreAsync(ULearn.StaffWS.listarEncargadosXUsuarioNombreRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/StaffWS/actualizarEncargadoRequest", ReplyAction="http://webservices.web.ulearn/StaffWS/actualizarEncargadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ULearn.StaffWS.actualizarEncargadoResponse actualizarEncargado(ULearn.StaffWS.actualizarEncargadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/StaffWS/actualizarEncargadoRequest", ReplyAction="http://webservices.web.ulearn/StaffWS/actualizarEncargadoResponse")]
        System.Threading.Tasks.Task<ULearn.StaffWS.actualizarEncargadoResponse> actualizarEncargadoAsync(ULearn.StaffWS.actualizarEncargadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/StaffWS/listarTodosAdministradoresRequest", ReplyAction="http://webservices.web.ulearn/StaffWS/listarTodosAdministradoresResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ULearn.StaffWS.listarTodosAdministradoresResponse listarTodosAdministradores(ULearn.StaffWS.listarTodosAdministradoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/StaffWS/listarTodosAdministradoresRequest", ReplyAction="http://webservices.web.ulearn/StaffWS/listarTodosAdministradoresResponse")]
        System.Threading.Tasks.Task<ULearn.StaffWS.listarTodosAdministradoresResponse> listarTodosAdministradoresAsync(ULearn.StaffWS.listarTodosAdministradoresRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/StaffWS/hallarEncargadoPorIdRequest", ReplyAction="http://webservices.web.ulearn/StaffWS/hallarEncargadoPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ULearn.StaffWS.hallarEncargadoPorIdResponse hallarEncargadoPorId(ULearn.StaffWS.hallarEncargadoPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/StaffWS/hallarEncargadoPorIdRequest", ReplyAction="http://webservices.web.ulearn/StaffWS/hallarEncargadoPorIdResponse")]
        System.Threading.Tasks.Task<ULearn.StaffWS.hallarEncargadoPorIdResponse> hallarEncargadoPorIdAsync(ULearn.StaffWS.hallarEncargadoPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/StaffWS/insertarAdministradorRequest", ReplyAction="http://webservices.web.ulearn/StaffWS/insertarAdministradorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ULearn.StaffWS.insertarAdministradorResponse insertarAdministrador(ULearn.StaffWS.insertarAdministradorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/StaffWS/insertarAdministradorRequest", ReplyAction="http://webservices.web.ulearn/StaffWS/insertarAdministradorResponse")]
        System.Threading.Tasks.Task<ULearn.StaffWS.insertarAdministradorResponse> insertarAdministradorAsync(ULearn.StaffWS.insertarAdministradorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/StaffWS/iniciarSesionRequest", ReplyAction="http://webservices.web.ulearn/StaffWS/iniciarSesionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ULearn.StaffWS.iniciarSesionResponse iniciarSesion(ULearn.StaffWS.iniciarSesionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/StaffWS/iniciarSesionRequest", ReplyAction="http://webservices.web.ulearn/StaffWS/iniciarSesionResponse")]
        System.Threading.Tasks.Task<ULearn.StaffWS.iniciarSesionResponse> iniciarSesionAsync(ULearn.StaffWS.iniciarSesionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarFotoPerfil", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class buscarFotoPerfilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public buscarFotoPerfilRequest() {
        }
        
        public buscarFotoPerfilRequest(int idUsuario) {
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarFotoPerfilResponse", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class buscarFotoPerfilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public buscarFotoPerfilResponse() {
        }
        
        public buscarFotoPerfilResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarAdministrador", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class eliminarAdministradorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idAdministrador;
        
        public eliminarAdministradorRequest() {
        }
        
        public eliminarAdministradorRequest(int idAdministrador) {
            this.idAdministrador = idAdministrador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarAdministradorResponse", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class eliminarAdministradorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarAdministradorResponse() {
        }
        
        public eliminarAdministradorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEncargado", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class eliminarEncargadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEncargado;
        
        public eliminarEncargadoRequest() {
        }
        
        public eliminarEncargadoRequest(int idEncargado) {
            this.idEncargado = idEncargado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEncargadoResponse", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class eliminarEncargadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarEncargadoResponse() {
        }
        
        public eliminarEncargadoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.web.ulearn/")]
    public partial class encargadoBiblioteca : empleado {
        
        private string titulo_trabajoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string titulo_trabajo {
            get {
                return this.titulo_trabajoField;
            }
            set {
                this.titulo_trabajoField = value;
                this.RaisePropertyChanged("titulo_trabajo");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(encargadoBiblioteca))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.web.ulearn/")]
    public abstract partial class empleado : usuario {
        
        private System.DateTime fechaContratacionField;
        
        private bool fechaContratacionFieldSpecified;
        
        private string horaEntradaField;
        
        private string horaSalidaField;
        
        private int idEmpleadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fechaContratacion {
            get {
                return this.fechaContratacionField;
            }
            set {
                this.fechaContratacionField = value;
                this.RaisePropertyChanged("fechaContratacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaContratacionSpecified {
            get {
                return this.fechaContratacionFieldSpecified;
            }
            set {
                this.fechaContratacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaContratacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string horaEntrada {
            get {
                return this.horaEntradaField;
            }
            set {
                this.horaEntradaField = value;
                this.RaisePropertyChanged("horaEntrada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string horaSalida {
            get {
                return this.horaSalidaField;
            }
            set {
                this.horaSalidaField = value;
                this.RaisePropertyChanged("horaSalida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idEmpleado {
            get {
                return this.idEmpleadoField;
            }
            set {
                this.idEmpleadoField = value;
                this.RaisePropertyChanged("idEmpleado");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(administrador))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(empleado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(encargadoBiblioteca))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.web.ulearn/")]
    public abstract partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string correoElectronicoField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private byte[] fotoField;
        
        private int idUsuarioField;
        
        private string nombreField;
        
        private string passwordField;
        
        private string saltField;
        
        private ushort sexoField;
        
        private string telefonoField;
        
        private ushort tipoUsuarioField;
        
        private string usuario1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                this.correoElectronicoField = value;
                this.RaisePropertyChanged("correoElectronico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=4)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string salt {
            get {
                return this.saltField;
            }
            set {
                this.saltField = value;
                this.RaisePropertyChanged("salt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public ushort sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public ushort tipoUsuario {
            get {
                return this.tipoUsuarioField;
            }
            set {
                this.tipoUsuarioField = value;
                this.RaisePropertyChanged("tipoUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("usuario", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string usuario1 {
            get {
                return this.usuario1Field;
            }
            set {
                this.usuario1Field = value;
                this.RaisePropertyChanged("usuario1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.web.ulearn/")]
    public partial class usuarioSesion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idUsuarioField;
        
        private ushort tipoUsuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ushort tipoUsuario {
            get {
                return this.tipoUsuarioField;
            }
            set {
                this.tipoUsuarioField = value;
                this.RaisePropertyChanged("tipoUsuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.web.ulearn/")]
    public partial class administrador : usuario {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosEncargados", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class listarTodosEncargadosRequest {
        
        public listarTodosEncargadosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosEncargadosResponse", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class listarTodosEncargadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ULearn.StaffWS.encargadoBiblioteca[] @return;
        
        public listarTodosEncargadosResponse() {
        }
        
        public listarTodosEncargadosResponse(ULearn.StaffWS.encargadoBiblioteca[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEncargado", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class insertarEncargadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ULearn.StaffWS.encargadoBiblioteca encargado;
        
        public insertarEncargadoRequest() {
        }
        
        public insertarEncargadoRequest(ULearn.StaffWS.encargadoBiblioteca encargado) {
            this.encargado = encargado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEncargadoResponse", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class insertarEncargadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarEncargadoResponse() {
        }
        
        public insertarEncargadoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hallarAdministradorPorId", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class hallarAdministradorPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idAdministrador;
        
        public hallarAdministradorPorIdRequest() {
        }
        
        public hallarAdministradorPorIdRequest(int idAdministrador) {
            this.idAdministrador = idAdministrador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hallarAdministradorPorIdResponse", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class hallarAdministradorPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ULearn.StaffWS.administrador @return;
        
        public hallarAdministradorPorIdResponse() {
        }
        
        public hallarAdministradorPorIdResponse(ULearn.StaffWS.administrador @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEncargadosXUsuarioNombre", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class listarEncargadosXUsuarioNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuarioNombre;
        
        public listarEncargadosXUsuarioNombreRequest() {
        }
        
        public listarEncargadosXUsuarioNombreRequest(string usuarioNombre) {
            this.usuarioNombre = usuarioNombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEncargadosXUsuarioNombreResponse", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class listarEncargadosXUsuarioNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ULearn.StaffWS.encargadoBiblioteca[] @return;
        
        public listarEncargadosXUsuarioNombreResponse() {
        }
        
        public listarEncargadosXUsuarioNombreResponse(ULearn.StaffWS.encargadoBiblioteca[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarEncargado", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class actualizarEncargadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ULearn.StaffWS.encargadoBiblioteca encargado;
        
        public actualizarEncargadoRequest() {
        }
        
        public actualizarEncargadoRequest(ULearn.StaffWS.encargadoBiblioteca encargado) {
            this.encargado = encargado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarEncargadoResponse", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class actualizarEncargadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarEncargadoResponse() {
        }
        
        public actualizarEncargadoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosAdministradores", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class listarTodosAdministradoresRequest {
        
        public listarTodosAdministradoresRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosAdministradoresResponse", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class listarTodosAdministradoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ULearn.StaffWS.administrador[] @return;
        
        public listarTodosAdministradoresResponse() {
        }
        
        public listarTodosAdministradoresResponse(ULearn.StaffWS.administrador[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hallarEncargadoPorId", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class hallarEncargadoPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEncargado;
        
        public hallarEncargadoPorIdRequest() {
        }
        
        public hallarEncargadoPorIdRequest(int idEncargado) {
            this.idEncargado = idEncargado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hallarEncargadoPorIdResponse", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class hallarEncargadoPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ULearn.StaffWS.encargadoBiblioteca @return;
        
        public hallarEncargadoPorIdResponse() {
        }
        
        public hallarEncargadoPorIdResponse(ULearn.StaffWS.encargadoBiblioteca @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarAdministrador", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class insertarAdministradorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ULearn.StaffWS.administrador administrador;
        
        public insertarAdministradorRequest() {
        }
        
        public insertarAdministradorRequest(ULearn.StaffWS.administrador administrador) {
            this.administrador = administrador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarAdministradorResponse", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class insertarAdministradorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarAdministradorResponse() {
        }
        
        public insertarAdministradorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="iniciarSesion", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class iniciarSesionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public iniciarSesionRequest() {
        }
        
        public iniciarSesionRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="iniciarSesionResponse", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class iniciarSesionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ULearn.StaffWS.usuarioSesion @return;
        
        public iniciarSesionResponse() {
        }
        
        public iniciarSesionResponse(ULearn.StaffWS.usuarioSesion @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StaffWSChannel : ULearn.StaffWS.StaffWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StaffWSClient : System.ServiceModel.ClientBase<ULearn.StaffWS.StaffWS>, ULearn.StaffWS.StaffWS {
        
        public StaffWSClient() {
        }
        
        public StaffWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StaffWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StaffWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StaffWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULearn.StaffWS.buscarFotoPerfilResponse ULearn.StaffWS.StaffWS.buscarFotoPerfil(ULearn.StaffWS.buscarFotoPerfilRequest request) {
            return base.Channel.buscarFotoPerfil(request);
        }
        
        public byte[] buscarFotoPerfil(int idUsuario) {
            ULearn.StaffWS.buscarFotoPerfilRequest inValue = new ULearn.StaffWS.buscarFotoPerfilRequest();
            inValue.idUsuario = idUsuario;
            ULearn.StaffWS.buscarFotoPerfilResponse retVal = ((ULearn.StaffWS.StaffWS)(this)).buscarFotoPerfil(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULearn.StaffWS.buscarFotoPerfilResponse> ULearn.StaffWS.StaffWS.buscarFotoPerfilAsync(ULearn.StaffWS.buscarFotoPerfilRequest request) {
            return base.Channel.buscarFotoPerfilAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULearn.StaffWS.buscarFotoPerfilResponse> buscarFotoPerfilAsync(int idUsuario) {
            ULearn.StaffWS.buscarFotoPerfilRequest inValue = new ULearn.StaffWS.buscarFotoPerfilRequest();
            inValue.idUsuario = idUsuario;
            return ((ULearn.StaffWS.StaffWS)(this)).buscarFotoPerfilAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULearn.StaffWS.eliminarAdministradorResponse ULearn.StaffWS.StaffWS.eliminarAdministrador(ULearn.StaffWS.eliminarAdministradorRequest request) {
            return base.Channel.eliminarAdministrador(request);
        }
        
        public int eliminarAdministrador(int idAdministrador) {
            ULearn.StaffWS.eliminarAdministradorRequest inValue = new ULearn.StaffWS.eliminarAdministradorRequest();
            inValue.idAdministrador = idAdministrador;
            ULearn.StaffWS.eliminarAdministradorResponse retVal = ((ULearn.StaffWS.StaffWS)(this)).eliminarAdministrador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULearn.StaffWS.eliminarAdministradorResponse> ULearn.StaffWS.StaffWS.eliminarAdministradorAsync(ULearn.StaffWS.eliminarAdministradorRequest request) {
            return base.Channel.eliminarAdministradorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULearn.StaffWS.eliminarAdministradorResponse> eliminarAdministradorAsync(int idAdministrador) {
            ULearn.StaffWS.eliminarAdministradorRequest inValue = new ULearn.StaffWS.eliminarAdministradorRequest();
            inValue.idAdministrador = idAdministrador;
            return ((ULearn.StaffWS.StaffWS)(this)).eliminarAdministradorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULearn.StaffWS.eliminarEncargadoResponse ULearn.StaffWS.StaffWS.eliminarEncargado(ULearn.StaffWS.eliminarEncargadoRequest request) {
            return base.Channel.eliminarEncargado(request);
        }
        
        public int eliminarEncargado(int idEncargado) {
            ULearn.StaffWS.eliminarEncargadoRequest inValue = new ULearn.StaffWS.eliminarEncargadoRequest();
            inValue.idEncargado = idEncargado;
            ULearn.StaffWS.eliminarEncargadoResponse retVal = ((ULearn.StaffWS.StaffWS)(this)).eliminarEncargado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULearn.StaffWS.eliminarEncargadoResponse> ULearn.StaffWS.StaffWS.eliminarEncargadoAsync(ULearn.StaffWS.eliminarEncargadoRequest request) {
            return base.Channel.eliminarEncargadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULearn.StaffWS.eliminarEncargadoResponse> eliminarEncargadoAsync(int idEncargado) {
            ULearn.StaffWS.eliminarEncargadoRequest inValue = new ULearn.StaffWS.eliminarEncargadoRequest();
            inValue.idEncargado = idEncargado;
            return ((ULearn.StaffWS.StaffWS)(this)).eliminarEncargadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULearn.StaffWS.listarTodosEncargadosResponse ULearn.StaffWS.StaffWS.listarTodosEncargados(ULearn.StaffWS.listarTodosEncargadosRequest request) {
            return base.Channel.listarTodosEncargados(request);
        }
        
        public ULearn.StaffWS.encargadoBiblioteca[] listarTodosEncargados() {
            ULearn.StaffWS.listarTodosEncargadosRequest inValue = new ULearn.StaffWS.listarTodosEncargadosRequest();
            ULearn.StaffWS.listarTodosEncargadosResponse retVal = ((ULearn.StaffWS.StaffWS)(this)).listarTodosEncargados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULearn.StaffWS.listarTodosEncargadosResponse> ULearn.StaffWS.StaffWS.listarTodosEncargadosAsync(ULearn.StaffWS.listarTodosEncargadosRequest request) {
            return base.Channel.listarTodosEncargadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULearn.StaffWS.listarTodosEncargadosResponse> listarTodosEncargadosAsync() {
            ULearn.StaffWS.listarTodosEncargadosRequest inValue = new ULearn.StaffWS.listarTodosEncargadosRequest();
            return ((ULearn.StaffWS.StaffWS)(this)).listarTodosEncargadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULearn.StaffWS.insertarEncargadoResponse ULearn.StaffWS.StaffWS.insertarEncargado(ULearn.StaffWS.insertarEncargadoRequest request) {
            return base.Channel.insertarEncargado(request);
        }
        
        public int insertarEncargado(ULearn.StaffWS.encargadoBiblioteca encargado) {
            ULearn.StaffWS.insertarEncargadoRequest inValue = new ULearn.StaffWS.insertarEncargadoRequest();
            inValue.encargado = encargado;
            ULearn.StaffWS.insertarEncargadoResponse retVal = ((ULearn.StaffWS.StaffWS)(this)).insertarEncargado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULearn.StaffWS.insertarEncargadoResponse> ULearn.StaffWS.StaffWS.insertarEncargadoAsync(ULearn.StaffWS.insertarEncargadoRequest request) {
            return base.Channel.insertarEncargadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULearn.StaffWS.insertarEncargadoResponse> insertarEncargadoAsync(ULearn.StaffWS.encargadoBiblioteca encargado) {
            ULearn.StaffWS.insertarEncargadoRequest inValue = new ULearn.StaffWS.insertarEncargadoRequest();
            inValue.encargado = encargado;
            return ((ULearn.StaffWS.StaffWS)(this)).insertarEncargadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULearn.StaffWS.hallarAdministradorPorIdResponse ULearn.StaffWS.StaffWS.hallarAdministradorPorId(ULearn.StaffWS.hallarAdministradorPorIdRequest request) {
            return base.Channel.hallarAdministradorPorId(request);
        }
        
        public ULearn.StaffWS.administrador hallarAdministradorPorId(int idAdministrador) {
            ULearn.StaffWS.hallarAdministradorPorIdRequest inValue = new ULearn.StaffWS.hallarAdministradorPorIdRequest();
            inValue.idAdministrador = idAdministrador;
            ULearn.StaffWS.hallarAdministradorPorIdResponse retVal = ((ULearn.StaffWS.StaffWS)(this)).hallarAdministradorPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULearn.StaffWS.hallarAdministradorPorIdResponse> ULearn.StaffWS.StaffWS.hallarAdministradorPorIdAsync(ULearn.StaffWS.hallarAdministradorPorIdRequest request) {
            return base.Channel.hallarAdministradorPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULearn.StaffWS.hallarAdministradorPorIdResponse> hallarAdministradorPorIdAsync(int idAdministrador) {
            ULearn.StaffWS.hallarAdministradorPorIdRequest inValue = new ULearn.StaffWS.hallarAdministradorPorIdRequest();
            inValue.idAdministrador = idAdministrador;
            return ((ULearn.StaffWS.StaffWS)(this)).hallarAdministradorPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULearn.StaffWS.listarEncargadosXUsuarioNombreResponse ULearn.StaffWS.StaffWS.listarEncargadosXUsuarioNombre(ULearn.StaffWS.listarEncargadosXUsuarioNombreRequest request) {
            return base.Channel.listarEncargadosXUsuarioNombre(request);
        }
        
        public ULearn.StaffWS.encargadoBiblioteca[] listarEncargadosXUsuarioNombre(string usuarioNombre) {
            ULearn.StaffWS.listarEncargadosXUsuarioNombreRequest inValue = new ULearn.StaffWS.listarEncargadosXUsuarioNombreRequest();
            inValue.usuarioNombre = usuarioNombre;
            ULearn.StaffWS.listarEncargadosXUsuarioNombreResponse retVal = ((ULearn.StaffWS.StaffWS)(this)).listarEncargadosXUsuarioNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULearn.StaffWS.listarEncargadosXUsuarioNombreResponse> ULearn.StaffWS.StaffWS.listarEncargadosXUsuarioNombreAsync(ULearn.StaffWS.listarEncargadosXUsuarioNombreRequest request) {
            return base.Channel.listarEncargadosXUsuarioNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULearn.StaffWS.listarEncargadosXUsuarioNombreResponse> listarEncargadosXUsuarioNombreAsync(string usuarioNombre) {
            ULearn.StaffWS.listarEncargadosXUsuarioNombreRequest inValue = new ULearn.StaffWS.listarEncargadosXUsuarioNombreRequest();
            inValue.usuarioNombre = usuarioNombre;
            return ((ULearn.StaffWS.StaffWS)(this)).listarEncargadosXUsuarioNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULearn.StaffWS.actualizarEncargadoResponse ULearn.StaffWS.StaffWS.actualizarEncargado(ULearn.StaffWS.actualizarEncargadoRequest request) {
            return base.Channel.actualizarEncargado(request);
        }
        
        public int actualizarEncargado(ULearn.StaffWS.encargadoBiblioteca encargado) {
            ULearn.StaffWS.actualizarEncargadoRequest inValue = new ULearn.StaffWS.actualizarEncargadoRequest();
            inValue.encargado = encargado;
            ULearn.StaffWS.actualizarEncargadoResponse retVal = ((ULearn.StaffWS.StaffWS)(this)).actualizarEncargado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULearn.StaffWS.actualizarEncargadoResponse> ULearn.StaffWS.StaffWS.actualizarEncargadoAsync(ULearn.StaffWS.actualizarEncargadoRequest request) {
            return base.Channel.actualizarEncargadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULearn.StaffWS.actualizarEncargadoResponse> actualizarEncargadoAsync(ULearn.StaffWS.encargadoBiblioteca encargado) {
            ULearn.StaffWS.actualizarEncargadoRequest inValue = new ULearn.StaffWS.actualizarEncargadoRequest();
            inValue.encargado = encargado;
            return ((ULearn.StaffWS.StaffWS)(this)).actualizarEncargadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULearn.StaffWS.listarTodosAdministradoresResponse ULearn.StaffWS.StaffWS.listarTodosAdministradores(ULearn.StaffWS.listarTodosAdministradoresRequest request) {
            return base.Channel.listarTodosAdministradores(request);
        }
        
        public ULearn.StaffWS.administrador[] listarTodosAdministradores() {
            ULearn.StaffWS.listarTodosAdministradoresRequest inValue = new ULearn.StaffWS.listarTodosAdministradoresRequest();
            ULearn.StaffWS.listarTodosAdministradoresResponse retVal = ((ULearn.StaffWS.StaffWS)(this)).listarTodosAdministradores(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULearn.StaffWS.listarTodosAdministradoresResponse> ULearn.StaffWS.StaffWS.listarTodosAdministradoresAsync(ULearn.StaffWS.listarTodosAdministradoresRequest request) {
            return base.Channel.listarTodosAdministradoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULearn.StaffWS.listarTodosAdministradoresResponse> listarTodosAdministradoresAsync() {
            ULearn.StaffWS.listarTodosAdministradoresRequest inValue = new ULearn.StaffWS.listarTodosAdministradoresRequest();
            return ((ULearn.StaffWS.StaffWS)(this)).listarTodosAdministradoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULearn.StaffWS.hallarEncargadoPorIdResponse ULearn.StaffWS.StaffWS.hallarEncargadoPorId(ULearn.StaffWS.hallarEncargadoPorIdRequest request) {
            return base.Channel.hallarEncargadoPorId(request);
        }
        
        public ULearn.StaffWS.encargadoBiblioteca hallarEncargadoPorId(int idEncargado) {
            ULearn.StaffWS.hallarEncargadoPorIdRequest inValue = new ULearn.StaffWS.hallarEncargadoPorIdRequest();
            inValue.idEncargado = idEncargado;
            ULearn.StaffWS.hallarEncargadoPorIdResponse retVal = ((ULearn.StaffWS.StaffWS)(this)).hallarEncargadoPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULearn.StaffWS.hallarEncargadoPorIdResponse> ULearn.StaffWS.StaffWS.hallarEncargadoPorIdAsync(ULearn.StaffWS.hallarEncargadoPorIdRequest request) {
            return base.Channel.hallarEncargadoPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULearn.StaffWS.hallarEncargadoPorIdResponse> hallarEncargadoPorIdAsync(int idEncargado) {
            ULearn.StaffWS.hallarEncargadoPorIdRequest inValue = new ULearn.StaffWS.hallarEncargadoPorIdRequest();
            inValue.idEncargado = idEncargado;
            return ((ULearn.StaffWS.StaffWS)(this)).hallarEncargadoPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULearn.StaffWS.insertarAdministradorResponse ULearn.StaffWS.StaffWS.insertarAdministrador(ULearn.StaffWS.insertarAdministradorRequest request) {
            return base.Channel.insertarAdministrador(request);
        }
        
        public int insertarAdministrador(ULearn.StaffWS.administrador administrador) {
            ULearn.StaffWS.insertarAdministradorRequest inValue = new ULearn.StaffWS.insertarAdministradorRequest();
            inValue.administrador = administrador;
            ULearn.StaffWS.insertarAdministradorResponse retVal = ((ULearn.StaffWS.StaffWS)(this)).insertarAdministrador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULearn.StaffWS.insertarAdministradorResponse> ULearn.StaffWS.StaffWS.insertarAdministradorAsync(ULearn.StaffWS.insertarAdministradorRequest request) {
            return base.Channel.insertarAdministradorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULearn.StaffWS.insertarAdministradorResponse> insertarAdministradorAsync(ULearn.StaffWS.administrador administrador) {
            ULearn.StaffWS.insertarAdministradorRequest inValue = new ULearn.StaffWS.insertarAdministradorRequest();
            inValue.administrador = administrador;
            return ((ULearn.StaffWS.StaffWS)(this)).insertarAdministradorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULearn.StaffWS.iniciarSesionResponse ULearn.StaffWS.StaffWS.iniciarSesion(ULearn.StaffWS.iniciarSesionRequest request) {
            return base.Channel.iniciarSesion(request);
        }
        
        public ULearn.StaffWS.usuarioSesion iniciarSesion(string arg0, string arg1) {
            ULearn.StaffWS.iniciarSesionRequest inValue = new ULearn.StaffWS.iniciarSesionRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ULearn.StaffWS.iniciarSesionResponse retVal = ((ULearn.StaffWS.StaffWS)(this)).iniciarSesion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULearn.StaffWS.iniciarSesionResponse> ULearn.StaffWS.StaffWS.iniciarSesionAsync(ULearn.StaffWS.iniciarSesionRequest request) {
            return base.Channel.iniciarSesionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULearn.StaffWS.iniciarSesionResponse> iniciarSesionAsync(string arg0, string arg1) {
            ULearn.StaffWS.iniciarSesionRequest inValue = new ULearn.StaffWS.iniciarSesionRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ULearn.StaffWS.StaffWS)(this)).iniciarSesionAsync(inValue);
        }
    }
}
