//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LP2Soft.RRHHWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", ConfigurationName="RRHHWS.RRHHWS")]
    public interface RRHHWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/listarEmpleadosPorDNINombreRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/listarEmpleadosPorDNINombreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.RRHHWS.listarEmpleadosPorDNINombreResponse listarEmpleadosPorDNINombre(LP2Soft.RRHHWS.listarEmpleadosPorDNINombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/listarEmpleadosPorDNINombreRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/listarEmpleadosPorDNINombreResponse")]
        System.Threading.Tasks.Task<LP2Soft.RRHHWS.listarEmpleadosPorDNINombreResponse> listarEmpleadosPorDNINombreAsync(LP2Soft.RRHHWS.listarEmpleadosPorDNINombreRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/helloRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.RRHHWS.helloResponse hello(LP2Soft.RRHHWS.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/helloRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/helloResponse")]
        System.Threading.Tasks.Task<LP2Soft.RRHHWS.helloResponse> helloAsync(LP2Soft.RRHHWS.helloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/listarTodasAreasRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/listarTodasAreasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.RRHHWS.listarTodasAreasResponse listarTodasAreas(LP2Soft.RRHHWS.listarTodasAreasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/listarTodasAreasRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/listarTodasAreasResponse")]
        System.Threading.Tasks.Task<LP2Soft.RRHHWS.listarTodasAreasResponse> listarTodasAreasAsync(LP2Soft.RRHHWS.listarTodasAreasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/insertarEmpleadoRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/insertarEmpleadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.RRHHWS.insertarEmpleadoResponse insertarEmpleado(LP2Soft.RRHHWS.insertarEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/insertarEmpleadoRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/insertarEmpleadoResponse")]
        System.Threading.Tasks.Task<LP2Soft.RRHHWS.insertarEmpleadoResponse> insertarEmpleadoAsync(LP2Soft.RRHHWS.insertarEmpleadoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/")]
    public partial class empleado : persona {
        
        private bool activoField;
        
        private area areaField;
        
        private string cargoField;
        
        private cuentaUsuario cuentaUsuarioField;
        
        private double sueldoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public area area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("area");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cargo {
            get {
                return this.cargoField;
            }
            set {
                this.cargoField = value;
                this.RaisePropertyChanged("cargo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public cuentaUsuario cuentaUsuario {
            get {
                return this.cuentaUsuarioField;
            }
            set {
                this.cuentaUsuarioField = value;
                this.RaisePropertyChanged("cuentaUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double sueldo {
            get {
                return this.sueldoField;
            }
            set {
                this.sueldoField = value;
                this.RaisePropertyChanged("sueldo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/")]
    public partial class area : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private empleado[] empleadosField;
        
        private int idAreaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("empleados", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public empleado[] empleados {
            get {
                return this.empleadosField;
            }
            set {
                this.empleadosField = value;
                this.RaisePropertyChanged("empleados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idArea {
            get {
                return this.idAreaField;
            }
            set {
                this.idAreaField = value;
                this.RaisePropertyChanged("idArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/")]
    public partial class cuentaUsuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private empleado empleadoField;
        
        private int idCuentaUsuarioField;
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public empleado empleado {
            get {
                return this.empleadoField;
            }
            set {
                this.empleadoField = value;
                this.RaisePropertyChanged("empleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idCuentaUsuario {
            get {
                return this.idCuentaUsuarioField;
            }
            set {
                this.idCuentaUsuarioField = value;
                this.RaisePropertyChanged("idCuentaUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(empleado))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoPaternoField;
        
        private string dNIField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private ushort generoField;
        
        private int idPersonaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DNI {
            get {
                return this.dNIField;
            }
            set {
                this.dNIField = value;
                this.RaisePropertyChanged("DNI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ushort genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpleadosPorDNINombre", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEmpleadosPorDNINombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DNInombre;
        
        public listarEmpleadosPorDNINombreRequest() {
        }
        
        public listarEmpleadosPorDNINombreRequest(string DNInombre) {
            this.DNInombre = DNInombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpleadosPorDNINombreResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEmpleadosPorDNINombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2Soft.RRHHWS.empleado[] @return;
        
        public listarEmpleadosPorDNINombreResponse() {
        }
        
        public listarEmpleadosPorDNINombreResponse(LP2Soft.RRHHWS.empleado[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasAreas", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasAreasRequest {
        
        public listarTodasAreasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasAreasResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasAreasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2Soft.RRHHWS.area[] @return;
        
        public listarTodasAreasResponse() {
        }
        
        public listarTodasAreasResponse(LP2Soft.RRHHWS.area[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEmpleado", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2Soft.RRHHWS.empleado empleado;
        
        public insertarEmpleadoRequest() {
        }
        
        public insertarEmpleadoRequest(LP2Soft.RRHHWS.empleado empleado) {
            this.empleado = empleado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEmpleadoResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarEmpleadoResponse() {
        }
        
        public insertarEmpleadoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RRHHWSChannel : LP2Soft.RRHHWS.RRHHWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RRHHWSClient : System.ServiceModel.ClientBase<LP2Soft.RRHHWS.RRHHWS>, LP2Soft.RRHHWS.RRHHWS {
        
        public RRHHWSClient() {
        }
        
        public RRHHWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RRHHWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RRHHWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RRHHWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.RRHHWS.listarEmpleadosPorDNINombreResponse LP2Soft.RRHHWS.RRHHWS.listarEmpleadosPorDNINombre(LP2Soft.RRHHWS.listarEmpleadosPorDNINombreRequest request) {
            return base.Channel.listarEmpleadosPorDNINombre(request);
        }
        
        public LP2Soft.RRHHWS.empleado[] listarEmpleadosPorDNINombre(string DNInombre) {
            LP2Soft.RRHHWS.listarEmpleadosPorDNINombreRequest inValue = new LP2Soft.RRHHWS.listarEmpleadosPorDNINombreRequest();
            inValue.DNInombre = DNInombre;
            LP2Soft.RRHHWS.listarEmpleadosPorDNINombreResponse retVal = ((LP2Soft.RRHHWS.RRHHWS)(this)).listarEmpleadosPorDNINombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.RRHHWS.listarEmpleadosPorDNINombreResponse> LP2Soft.RRHHWS.RRHHWS.listarEmpleadosPorDNINombreAsync(LP2Soft.RRHHWS.listarEmpleadosPorDNINombreRequest request) {
            return base.Channel.listarEmpleadosPorDNINombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.RRHHWS.listarEmpleadosPorDNINombreResponse> listarEmpleadosPorDNINombreAsync(string DNInombre) {
            LP2Soft.RRHHWS.listarEmpleadosPorDNINombreRequest inValue = new LP2Soft.RRHHWS.listarEmpleadosPorDNINombreRequest();
            inValue.DNInombre = DNInombre;
            return ((LP2Soft.RRHHWS.RRHHWS)(this)).listarEmpleadosPorDNINombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.RRHHWS.helloResponse LP2Soft.RRHHWS.RRHHWS.hello(LP2Soft.RRHHWS.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            LP2Soft.RRHHWS.helloRequest inValue = new LP2Soft.RRHHWS.helloRequest();
            inValue.name = name;
            LP2Soft.RRHHWS.helloResponse retVal = ((LP2Soft.RRHHWS.RRHHWS)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.RRHHWS.helloResponse> LP2Soft.RRHHWS.RRHHWS.helloAsync(LP2Soft.RRHHWS.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.RRHHWS.helloResponse> helloAsync(string name) {
            LP2Soft.RRHHWS.helloRequest inValue = new LP2Soft.RRHHWS.helloRequest();
            inValue.name = name;
            return ((LP2Soft.RRHHWS.RRHHWS)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.RRHHWS.listarTodasAreasResponse LP2Soft.RRHHWS.RRHHWS.listarTodasAreas(LP2Soft.RRHHWS.listarTodasAreasRequest request) {
            return base.Channel.listarTodasAreas(request);
        }
        
        public LP2Soft.RRHHWS.area[] listarTodasAreas() {
            LP2Soft.RRHHWS.listarTodasAreasRequest inValue = new LP2Soft.RRHHWS.listarTodasAreasRequest();
            LP2Soft.RRHHWS.listarTodasAreasResponse retVal = ((LP2Soft.RRHHWS.RRHHWS)(this)).listarTodasAreas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.RRHHWS.listarTodasAreasResponse> LP2Soft.RRHHWS.RRHHWS.listarTodasAreasAsync(LP2Soft.RRHHWS.listarTodasAreasRequest request) {
            return base.Channel.listarTodasAreasAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.RRHHWS.listarTodasAreasResponse> listarTodasAreasAsync() {
            LP2Soft.RRHHWS.listarTodasAreasRequest inValue = new LP2Soft.RRHHWS.listarTodasAreasRequest();
            return ((LP2Soft.RRHHWS.RRHHWS)(this)).listarTodasAreasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.RRHHWS.insertarEmpleadoResponse LP2Soft.RRHHWS.RRHHWS.insertarEmpleado(LP2Soft.RRHHWS.insertarEmpleadoRequest request) {
            return base.Channel.insertarEmpleado(request);
        }
        
        public int insertarEmpleado(LP2Soft.RRHHWS.empleado empleado) {
            LP2Soft.RRHHWS.insertarEmpleadoRequest inValue = new LP2Soft.RRHHWS.insertarEmpleadoRequest();
            inValue.empleado = empleado;
            LP2Soft.RRHHWS.insertarEmpleadoResponse retVal = ((LP2Soft.RRHHWS.RRHHWS)(this)).insertarEmpleado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.RRHHWS.insertarEmpleadoResponse> LP2Soft.RRHHWS.RRHHWS.insertarEmpleadoAsync(LP2Soft.RRHHWS.insertarEmpleadoRequest request) {
            return base.Channel.insertarEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.RRHHWS.insertarEmpleadoResponse> insertarEmpleadoAsync(LP2Soft.RRHHWS.empleado empleado) {
            LP2Soft.RRHHWS.insertarEmpleadoRequest inValue = new LP2Soft.RRHHWS.insertarEmpleadoRequest();
            inValue.empleado = empleado;
            return ((LP2Soft.RRHHWS.RRHHWS)(this)).insertarEmpleadoAsync(inValue);
        }
    }
}
