//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ULearn.ReportesWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.web.ulearn/", ConfigurationName="ReportesWS.ReportesWS")]
    public interface ReportesWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/ReportesWS/generarReporteHorarioCursoRequest", ReplyAction="http://webservices.web.ulearn/ReportesWS/generarReporteHorarioCursoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ULearn.ReportesWS.generarReporteHorarioCursoResponse generarReporteHorarioCurso(ULearn.ReportesWS.generarReporteHorarioCursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/ReportesWS/generarReporteHorarioCursoRequest", ReplyAction="http://webservices.web.ulearn/ReportesWS/generarReporteHorarioCursoResponse")]
        System.Threading.Tasks.Task<ULearn.ReportesWS.generarReporteHorarioCursoResponse> generarReporteHorarioCursoAsync(ULearn.ReportesWS.generarReporteHorarioCursoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/ReportesWS/generarReportePrestamosRequest", ReplyAction="http://webservices.web.ulearn/ReportesWS/generarReportePrestamosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ULearn.ReportesWS.generarReportePrestamosResponse generarReportePrestamos(ULearn.ReportesWS.generarReportePrestamosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/ReportesWS/generarReportePrestamosRequest", ReplyAction="http://webservices.web.ulearn/ReportesWS/generarReportePrestamosResponse")]
        System.Threading.Tasks.Task<ULearn.ReportesWS.generarReportePrestamosResponse> generarReportePrestamosAsync(ULearn.ReportesWS.generarReportePrestamosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/ReportesWS/generarReporteHistorialAcademicoAlumnoRe" +
            "quest", ReplyAction="http://webservices.web.ulearn/ReportesWS/generarReporteHistorialAcademicoAlumnoRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ULearn.ReportesWS.generarReporteHistorialAcademicoAlumnoResponse generarReporteHistorialAcademicoAlumno(ULearn.ReportesWS.generarReporteHistorialAcademicoAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.web.ulearn/ReportesWS/generarReporteHistorialAcademicoAlumnoRe" +
            "quest", ReplyAction="http://webservices.web.ulearn/ReportesWS/generarReporteHistorialAcademicoAlumnoRe" +
            "sponse")]
        System.Threading.Tasks.Task<ULearn.ReportesWS.generarReporteHistorialAcademicoAlumnoResponse> generarReporteHistorialAcademicoAlumnoAsync(ULearn.ReportesWS.generarReporteHistorialAcademicoAlumnoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.web.ulearn/")]
    public partial class horario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private alumno[] alumnosField;
        
        private int aprobadosField;
        
        private string codigoField;
        
        private curso cursoField;
        
        private diaSemana diaField;
        
        private bool diaFieldSpecified;
        
        private docente[] docentesField;
        
        private string horaFinField;
        
        private string horaInicioField;
        
        private int idHorarioField;
        
        private int matriculadosField;
        
        private double mediaField;
        
        private int tiempoToleranciaField;
        
        private ushort tipoHorarioField;
        
        private int vacantesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("alumnos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public alumno[] alumnos {
            get {
                return this.alumnosField;
            }
            set {
                this.alumnosField = value;
                this.RaisePropertyChanged("alumnos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int aprobados {
            get {
                return this.aprobadosField;
            }
            set {
                this.aprobadosField = value;
                this.RaisePropertyChanged("aprobados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public curso curso {
            get {
                return this.cursoField;
            }
            set {
                this.cursoField = value;
                this.RaisePropertyChanged("curso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public diaSemana dia {
            get {
                return this.diaField;
            }
            set {
                this.diaField = value;
                this.RaisePropertyChanged("dia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool diaSpecified {
            get {
                return this.diaFieldSpecified;
            }
            set {
                this.diaFieldSpecified = value;
                this.RaisePropertyChanged("diaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("docentes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public docente[] docentes {
            get {
                return this.docentesField;
            }
            set {
                this.docentesField = value;
                this.RaisePropertyChanged("docentes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string horaFin {
            get {
                return this.horaFinField;
            }
            set {
                this.horaFinField = value;
                this.RaisePropertyChanged("horaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string horaInicio {
            get {
                return this.horaInicioField;
            }
            set {
                this.horaInicioField = value;
                this.RaisePropertyChanged("horaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int idHorario {
            get {
                return this.idHorarioField;
            }
            set {
                this.idHorarioField = value;
                this.RaisePropertyChanged("idHorario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int matriculados {
            get {
                return this.matriculadosField;
            }
            set {
                this.matriculadosField = value;
                this.RaisePropertyChanged("matriculados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public double media {
            get {
                return this.mediaField;
            }
            set {
                this.mediaField = value;
                this.RaisePropertyChanged("media");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int tiempoTolerancia {
            get {
                return this.tiempoToleranciaField;
            }
            set {
                this.tiempoToleranciaField = value;
                this.RaisePropertyChanged("tiempoTolerancia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public ushort tipoHorario {
            get {
                return this.tipoHorarioField;
            }
            set {
                this.tipoHorarioField = value;
                this.RaisePropertyChanged("tipoHorario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public int vacantes {
            get {
                return this.vacantesField;
            }
            set {
                this.vacantesField = value;
                this.RaisePropertyChanged("vacantes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.web.ulearn/")]
    public partial class alumno : usuario {
        
        private carrera carreraField;
        
        private int codAlumnoField;
        
        private string codigoAlumnoField;
        
        private double creditosTotalField;
        
        private int cursosTotalField;
        
        private int esDeudorField;
        
        private evaluacion[] evaluacionesField;
        
        private historialAcademico historialAcademicoField;
        
        private horario[] horariosInscritosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public carrera carrera {
            get {
                return this.carreraField;
            }
            set {
                this.carreraField = value;
                this.RaisePropertyChanged("carrera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codAlumno {
            get {
                return this.codAlumnoField;
            }
            set {
                this.codAlumnoField = value;
                this.RaisePropertyChanged("codAlumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoAlumno {
            get {
                return this.codigoAlumnoField;
            }
            set {
                this.codigoAlumnoField = value;
                this.RaisePropertyChanged("codigoAlumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double creditosTotal {
            get {
                return this.creditosTotalField;
            }
            set {
                this.creditosTotalField = value;
                this.RaisePropertyChanged("creditosTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int cursosTotal {
            get {
                return this.cursosTotalField;
            }
            set {
                this.cursosTotalField = value;
                this.RaisePropertyChanged("cursosTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int esDeudor {
            get {
                return this.esDeudorField;
            }
            set {
                this.esDeudorField = value;
                this.RaisePropertyChanged("esDeudor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("evaluaciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public evaluacion[] evaluaciones {
            get {
                return this.evaluacionesField;
            }
            set {
                this.evaluacionesField = value;
                this.RaisePropertyChanged("evaluaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public historialAcademico historialAcademico {
            get {
                return this.historialAcademicoField;
            }
            set {
                this.historialAcademicoField = value;
                this.RaisePropertyChanged("historialAcademico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("horariosInscritos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public horario[] horariosInscritos {
            get {
                return this.horariosInscritosField;
            }
            set {
                this.horariosInscritosField = value;
                this.RaisePropertyChanged("horariosInscritos");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.web.ulearn/")]
    public partial class carrera : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime cambioMallaField;
        
        private bool cambioMallaFieldSpecified;
        
        private double creditosField;
        
        private curso[] cursosField;
        
        private int cursosTotalesField;
        
        private bool esAcreditadaField;
        
        private facultad facultadField;
        
        private int idCarreraField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime cambioMalla {
            get {
                return this.cambioMallaField;
            }
            set {
                this.cambioMallaField = value;
                this.RaisePropertyChanged("cambioMalla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cambioMallaSpecified {
            get {
                return this.cambioMallaFieldSpecified;
            }
            set {
                this.cambioMallaFieldSpecified = value;
                this.RaisePropertyChanged("cambioMallaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double creditos {
            get {
                return this.creditosField;
            }
            set {
                this.creditosField = value;
                this.RaisePropertyChanged("creditos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cursos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public curso[] cursos {
            get {
                return this.cursosField;
            }
            set {
                this.cursosField = value;
                this.RaisePropertyChanged("cursos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int cursosTotales {
            get {
                return this.cursosTotalesField;
            }
            set {
                this.cursosTotalesField = value;
                this.RaisePropertyChanged("cursosTotales");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool esAcreditada {
            get {
                return this.esAcreditadaField;
            }
            set {
                this.esAcreditadaField = value;
                this.RaisePropertyChanged("esAcreditada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public facultad facultad {
            get {
                return this.facultadField;
            }
            set {
                this.facultadField = value;
                this.RaisePropertyChanged("facultad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idCarrera {
            get {
                return this.idCarreraField;
            }
            set {
                this.idCarreraField = value;
                this.RaisePropertyChanged("idCarrera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.web.ulearn/")]
    public partial class curso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codCursoField;
        
        private double creditosField;
        
        private docente[] docentesField;
        
        private int esElectivoField;
        
        private evaluacion[] evaluacionesField;
        
        private horario[] horariosField;
        
        private int idCursoField;
        
        private string nombreField;
        
        private semestre semestreDictadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codCurso {
            get {
                return this.codCursoField;
            }
            set {
                this.codCursoField = value;
                this.RaisePropertyChanged("codCurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double creditos {
            get {
                return this.creditosField;
            }
            set {
                this.creditosField = value;
                this.RaisePropertyChanged("creditos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("docentes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public docente[] docentes {
            get {
                return this.docentesField;
            }
            set {
                this.docentesField = value;
                this.RaisePropertyChanged("docentes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int esElectivo {
            get {
                return this.esElectivoField;
            }
            set {
                this.esElectivoField = value;
                this.RaisePropertyChanged("esElectivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("evaluaciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public evaluacion[] evaluaciones {
            get {
                return this.evaluacionesField;
            }
            set {
                this.evaluacionesField = value;
                this.RaisePropertyChanged("evaluaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("horarios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public horario[] horarios {
            get {
                return this.horariosField;
            }
            set {
                this.horariosField = value;
                this.RaisePropertyChanged("horarios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idCurso {
            get {
                return this.idCursoField;
            }
            set {
                this.idCursoField = value;
                this.RaisePropertyChanged("idCurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public semestre semestreDictado {
            get {
                return this.semestreDictadoField;
            }
            set {
                this.semestreDictadoField = value;
                this.RaisePropertyChanged("semestreDictado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.web.ulearn/")]
    public partial class docente : empleado {
        
        private curso[] cursosDictarField;
        
        private int esDeudorField;
        
        private facultad facultadField;
        
        private string gradoAcademicoField;
        
        private string interesesField;
        
        private string oficinaField;
        
        private string tipoDocenteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cursosDictar", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public curso[] cursosDictar {
            get {
                return this.cursosDictarField;
            }
            set {
                this.cursosDictarField = value;
                this.RaisePropertyChanged("cursosDictar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int esDeudor {
            get {
                return this.esDeudorField;
            }
            set {
                this.esDeudorField = value;
                this.RaisePropertyChanged("esDeudor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public facultad facultad {
            get {
                return this.facultadField;
            }
            set {
                this.facultadField = value;
                this.RaisePropertyChanged("facultad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string gradoAcademico {
            get {
                return this.gradoAcademicoField;
            }
            set {
                this.gradoAcademicoField = value;
                this.RaisePropertyChanged("gradoAcademico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string intereses {
            get {
                return this.interesesField;
            }
            set {
                this.interesesField = value;
                this.RaisePropertyChanged("intereses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string oficina {
            get {
                return this.oficinaField;
            }
            set {
                this.oficinaField = value;
                this.RaisePropertyChanged("oficina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string tipoDocente {
            get {
                return this.tipoDocenteField;
            }
            set {
                this.tipoDocenteField = value;
                this.RaisePropertyChanged("tipoDocente");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.web.ulearn/")]
    public partial class facultad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string anexoField;
        
        private carrera[] carrerasField;
        
        private int idFacultadField;
        
        private int inscritosField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string anexo {
            get {
                return this.anexoField;
            }
            set {
                this.anexoField = value;
                this.RaisePropertyChanged("anexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("carreras", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public carrera[] carreras {
            get {
                return this.carrerasField;
            }
            set {
                this.carrerasField = value;
                this.RaisePropertyChanged("carreras");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idFacultad {
            get {
                return this.idFacultadField;
            }
            set {
                this.idFacultadField = value;
                this.RaisePropertyChanged("idFacultad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int inscritos {
            get {
                return this.inscritosField;
            }
            set {
                this.inscritosField = value;
                this.RaisePropertyChanged("inscritos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.web.ulearn/")]
    public partial class historialAcademico : object, System.ComponentModel.INotifyPropertyChanged {
        
        private alumno alumnoField;
        
        private double cantCredAprobField;
        
        private double cantCredTotalField;
        
        private int cantCurAprobadosField;
        
        private int cantCurTotalField;
        
        private int nivelAcademicoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public alumno alumno {
            get {
                return this.alumnoField;
            }
            set {
                this.alumnoField = value;
                this.RaisePropertyChanged("alumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double cantCredAprob {
            get {
                return this.cantCredAprobField;
            }
            set {
                this.cantCredAprobField = value;
                this.RaisePropertyChanged("cantCredAprob");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double cantCredTotal {
            get {
                return this.cantCredTotalField;
            }
            set {
                this.cantCredTotalField = value;
                this.RaisePropertyChanged("cantCredTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int cantCurAprobados {
            get {
                return this.cantCurAprobadosField;
            }
            set {
                this.cantCurAprobadosField = value;
                this.RaisePropertyChanged("cantCurAprobados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int cantCurTotal {
            get {
                return this.cantCurTotalField;
            }
            set {
                this.cantCurTotalField = value;
                this.RaisePropertyChanged("cantCurTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int nivelAcademico {
            get {
                return this.nivelAcademicoField;
            }
            set {
                this.nivelAcademicoField = value;
                this.RaisePropertyChanged("nivelAcademico");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.web.ulearn/")]
    public partial class semestre : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool esRegularField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idSemestreField;
        
        private string semestre1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool esRegular {
            get {
                return this.esRegularField;
            }
            set {
                this.esRegularField = value;
                this.RaisePropertyChanged("esRegular");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idSemestre {
            get {
                return this.idSemestreField;
            }
            set {
                this.idSemestreField = value;
                this.RaisePropertyChanged("idSemestre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("semestre", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string semestre1 {
            get {
                return this.semestre1Field;
            }
            set {
                this.semestre1Field = value;
                this.RaisePropertyChanged("semestre1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.web.ulearn/")]
    public partial class reclamo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string descripcionField;
        
        private evaluacion evaluacionField;
        
        private System.DateTime fechaReclamoField;
        
        private bool fechaReclamoFieldSpecified;
        
        private int idReclamoField;
        
        private string respuestaField;
        
        private bool validoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public evaluacion evaluacion {
            get {
                return this.evaluacionField;
            }
            set {
                this.evaluacionField = value;
                this.RaisePropertyChanged("evaluacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaReclamo {
            get {
                return this.fechaReclamoField;
            }
            set {
                this.fechaReclamoField = value;
                this.RaisePropertyChanged("fechaReclamo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaReclamoSpecified {
            get {
                return this.fechaReclamoFieldSpecified;
            }
            set {
                this.fechaReclamoFieldSpecified = value;
                this.RaisePropertyChanged("fechaReclamoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idReclamo {
            get {
                return this.idReclamoField;
            }
            set {
                this.idReclamoField = value;
                this.RaisePropertyChanged("idReclamo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
                this.RaisePropertyChanged("respuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool valido {
            get {
                return this.validoField;
            }
            set {
                this.validoField = value;
                this.RaisePropertyChanged("valido");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.web.ulearn/")]
    public partial class evaluacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private alumno alumnoField;
        
        private ushort asistioField;
        
        private curso cursoField;
        
        private int idEvaluacionField;
        
        private nombreEvaluacion nombreEvaluacionField;
        
        private bool nombreEvaluacionFieldSpecified;
        
        private double notaField;
        
        private reclamo reclamoField;
        
        private semestre semestreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public alumno alumno {
            get {
                return this.alumnoField;
            }
            set {
                this.alumnoField = value;
                this.RaisePropertyChanged("alumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ushort asistio {
            get {
                return this.asistioField;
            }
            set {
                this.asistioField = value;
                this.RaisePropertyChanged("asistio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public curso curso {
            get {
                return this.cursoField;
            }
            set {
                this.cursoField = value;
                this.RaisePropertyChanged("curso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idEvaluacion {
            get {
                return this.idEvaluacionField;
            }
            set {
                this.idEvaluacionField = value;
                this.RaisePropertyChanged("idEvaluacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public nombreEvaluacion nombreEvaluacion {
            get {
                return this.nombreEvaluacionField;
            }
            set {
                this.nombreEvaluacionField = value;
                this.RaisePropertyChanged("nombreEvaluacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nombreEvaluacionSpecified {
            get {
                return this.nombreEvaluacionFieldSpecified;
            }
            set {
                this.nombreEvaluacionFieldSpecified = value;
                this.RaisePropertyChanged("nombreEvaluacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double nota {
            get {
                return this.notaField;
            }
            set {
                this.notaField = value;
                this.RaisePropertyChanged("nota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public reclamo reclamo {
            get {
                return this.reclamoField;
            }
            set {
                this.reclamoField = value;
                this.RaisePropertyChanged("reclamo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public semestre semestre {
            get {
                return this.semestreField;
            }
            set {
                this.semestreField = value;
                this.RaisePropertyChanged("semestre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.web.ulearn/")]
    public enum nombreEvaluacion {
        
        /// <remarks/>
        PC1,
        
        /// <remarks/>
        PC2,
        
        /// <remarks/>
        PC3,
        
        /// <remarks/>
        PC4,
        
        /// <remarks/>
        EX1,
        
        /// <remarks/>
        EX2,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(empleado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(docente))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(alumno))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.web.ulearn/")]
    public abstract partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string correoElectronicoField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private byte[] fotoField;
        
        private int idUsuarioField;
        
        private string nombreField;
        
        private string passwordField;
        
        private string saltField;
        
        private ushort sexoField;
        
        private string telefonoField;
        
        private ushort tipoUsuarioField;
        
        private string usuario1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                this.correoElectronicoField = value;
                this.RaisePropertyChanged("correoElectronico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=4)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string salt {
            get {
                return this.saltField;
            }
            set {
                this.saltField = value;
                this.RaisePropertyChanged("salt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public ushort sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public ushort tipoUsuario {
            get {
                return this.tipoUsuarioField;
            }
            set {
                this.tipoUsuarioField = value;
                this.RaisePropertyChanged("tipoUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("usuario", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string usuario1 {
            get {
                return this.usuario1Field;
            }
            set {
                this.usuario1Field = value;
                this.RaisePropertyChanged("usuario1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(docente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.web.ulearn/")]
    public abstract partial class empleado : usuario {
        
        private System.DateTime fechaContratacionField;
        
        private bool fechaContratacionFieldSpecified;
        
        private string horaEntradaField;
        
        private string horaSalidaField;
        
        private int idEmpleadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fechaContratacion {
            get {
                return this.fechaContratacionField;
            }
            set {
                this.fechaContratacionField = value;
                this.RaisePropertyChanged("fechaContratacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaContratacionSpecified {
            get {
                return this.fechaContratacionFieldSpecified;
            }
            set {
                this.fechaContratacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaContratacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string horaEntrada {
            get {
                return this.horaEntradaField;
            }
            set {
                this.horaEntradaField = value;
                this.RaisePropertyChanged("horaEntrada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string horaSalida {
            get {
                return this.horaSalidaField;
            }
            set {
                this.horaSalidaField = value;
                this.RaisePropertyChanged("horaSalida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idEmpleado {
            get {
                return this.idEmpleadoField;
            }
            set {
                this.idEmpleadoField = value;
                this.RaisePropertyChanged("idEmpleado");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.web.ulearn/")]
    public enum diaSemana {
        
        /// <remarks/>
        Lunes,
        
        /// <remarks/>
        Martes,
        
        /// <remarks/>
        Miercoles,
        
        /// <remarks/>
        Jueves,
        
        /// <remarks/>
        Viernes,
        
        /// <remarks/>
        Sabado,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteHorarioCurso", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class generarReporteHorarioCursoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ULearn.ReportesWS.horario horario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ULearn.ReportesWS.curso curso;
        
        public generarReporteHorarioCursoRequest() {
        }
        
        public generarReporteHorarioCursoRequest(ULearn.ReportesWS.horario horario, ULearn.ReportesWS.curso curso) {
            this.horario = horario;
            this.curso = curso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteHorarioCursoResponse", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class generarReporteHorarioCursoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public generarReporteHorarioCursoResponse() {
        }
        
        public generarReporteHorarioCursoResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReportePrestamos", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class generarReportePrestamosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int modo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idBiblioteca;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaFin;
        
        public generarReportePrestamosRequest() {
        }
        
        public generarReportePrestamosRequest(int modo, int idBiblioteca, System.DateTime fechaInicio, System.DateTime fechaFin) {
            this.modo = modo;
            this.idBiblioteca = idBiblioteca;
            this.fechaInicio = fechaInicio;
            this.fechaFin = fechaFin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReportePrestamosResponse", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class generarReportePrestamosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public generarReportePrestamosResponse() {
        }
        
        public generarReportePrestamosResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteHistorialAcademicoAlumno", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class generarReporteHistorialAcademicoAlumnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idAlumno;
        
        public generarReporteHistorialAcademicoAlumnoRequest() {
        }
        
        public generarReporteHistorialAcademicoAlumnoRequest(int idAlumno) {
            this.idAlumno = idAlumno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteHistorialAcademicoAlumnoResponse", WrapperNamespace="http://webservices.web.ulearn/", IsWrapped=true)]
    public partial class generarReporteHistorialAcademicoAlumnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.web.ulearn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public generarReporteHistorialAcademicoAlumnoResponse() {
        }
        
        public generarReporteHistorialAcademicoAlumnoResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReportesWSChannel : ULearn.ReportesWS.ReportesWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportesWSClient : System.ServiceModel.ClientBase<ULearn.ReportesWS.ReportesWS>, ULearn.ReportesWS.ReportesWS {
        
        public ReportesWSClient() {
        }
        
        public ReportesWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportesWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportesWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportesWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULearn.ReportesWS.generarReporteHorarioCursoResponse ULearn.ReportesWS.ReportesWS.generarReporteHorarioCurso(ULearn.ReportesWS.generarReporteHorarioCursoRequest request) {
            return base.Channel.generarReporteHorarioCurso(request);
        }
        
        public byte[] generarReporteHorarioCurso(ULearn.ReportesWS.horario horario, ULearn.ReportesWS.curso curso) {
            ULearn.ReportesWS.generarReporteHorarioCursoRequest inValue = new ULearn.ReportesWS.generarReporteHorarioCursoRequest();
            inValue.horario = horario;
            inValue.curso = curso;
            ULearn.ReportesWS.generarReporteHorarioCursoResponse retVal = ((ULearn.ReportesWS.ReportesWS)(this)).generarReporteHorarioCurso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULearn.ReportesWS.generarReporteHorarioCursoResponse> ULearn.ReportesWS.ReportesWS.generarReporteHorarioCursoAsync(ULearn.ReportesWS.generarReporteHorarioCursoRequest request) {
            return base.Channel.generarReporteHorarioCursoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULearn.ReportesWS.generarReporteHorarioCursoResponse> generarReporteHorarioCursoAsync(ULearn.ReportesWS.horario horario, ULearn.ReportesWS.curso curso) {
            ULearn.ReportesWS.generarReporteHorarioCursoRequest inValue = new ULearn.ReportesWS.generarReporteHorarioCursoRequest();
            inValue.horario = horario;
            inValue.curso = curso;
            return ((ULearn.ReportesWS.ReportesWS)(this)).generarReporteHorarioCursoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULearn.ReportesWS.generarReportePrestamosResponse ULearn.ReportesWS.ReportesWS.generarReportePrestamos(ULearn.ReportesWS.generarReportePrestamosRequest request) {
            return base.Channel.generarReportePrestamos(request);
        }
        
        public byte[] generarReportePrestamos(int modo, int idBiblioteca, System.DateTime fechaInicio, System.DateTime fechaFin) {
            ULearn.ReportesWS.generarReportePrestamosRequest inValue = new ULearn.ReportesWS.generarReportePrestamosRequest();
            inValue.modo = modo;
            inValue.idBiblioteca = idBiblioteca;
            inValue.fechaInicio = fechaInicio;
            inValue.fechaFin = fechaFin;
            ULearn.ReportesWS.generarReportePrestamosResponse retVal = ((ULearn.ReportesWS.ReportesWS)(this)).generarReportePrestamos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULearn.ReportesWS.generarReportePrestamosResponse> ULearn.ReportesWS.ReportesWS.generarReportePrestamosAsync(ULearn.ReportesWS.generarReportePrestamosRequest request) {
            return base.Channel.generarReportePrestamosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULearn.ReportesWS.generarReportePrestamosResponse> generarReportePrestamosAsync(int modo, int idBiblioteca, System.DateTime fechaInicio, System.DateTime fechaFin) {
            ULearn.ReportesWS.generarReportePrestamosRequest inValue = new ULearn.ReportesWS.generarReportePrestamosRequest();
            inValue.modo = modo;
            inValue.idBiblioteca = idBiblioteca;
            inValue.fechaInicio = fechaInicio;
            inValue.fechaFin = fechaFin;
            return ((ULearn.ReportesWS.ReportesWS)(this)).generarReportePrestamosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ULearn.ReportesWS.generarReporteHistorialAcademicoAlumnoResponse ULearn.ReportesWS.ReportesWS.generarReporteHistorialAcademicoAlumno(ULearn.ReportesWS.generarReporteHistorialAcademicoAlumnoRequest request) {
            return base.Channel.generarReporteHistorialAcademicoAlumno(request);
        }
        
        public byte[] generarReporteHistorialAcademicoAlumno(int idAlumno) {
            ULearn.ReportesWS.generarReporteHistorialAcademicoAlumnoRequest inValue = new ULearn.ReportesWS.generarReporteHistorialAcademicoAlumnoRequest();
            inValue.idAlumno = idAlumno;
            ULearn.ReportesWS.generarReporteHistorialAcademicoAlumnoResponse retVal = ((ULearn.ReportesWS.ReportesWS)(this)).generarReporteHistorialAcademicoAlumno(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ULearn.ReportesWS.generarReporteHistorialAcademicoAlumnoResponse> ULearn.ReportesWS.ReportesWS.generarReporteHistorialAcademicoAlumnoAsync(ULearn.ReportesWS.generarReporteHistorialAcademicoAlumnoRequest request) {
            return base.Channel.generarReporteHistorialAcademicoAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ULearn.ReportesWS.generarReporteHistorialAcademicoAlumnoResponse> generarReporteHistorialAcademicoAlumnoAsync(int idAlumno) {
            ULearn.ReportesWS.generarReporteHistorialAcademicoAlumnoRequest inValue = new ULearn.ReportesWS.generarReporteHistorialAcademicoAlumnoRequest();
            inValue.idAlumno = idAlumno;
            return ((ULearn.ReportesWS.ReportesWS)(this)).generarReporteHistorialAcademicoAlumnoAsync(inValue);
        }
    }
}
